### ISSUE TITLE
Unnecessary underscore

### ISSUE THREAD

**Issue by RealWeeks** [ga-wdi-boston/js-objects-constructors#19]
```
const usePower = function () {
  return this._power;
};
```

**Comment by jrhorn424** [comment]
Underscores are typically used to denote something should be "hidden".

This is another `#teachableMoment`.

**Comment by jrhorn424** [comment]
http://stackoverflow.com/questions/8288756/in-javascript-what-does-this-underscore-mean

**Comment by RealWeeks** [comment]
@gaand asked me to open this

**Comment by gaand** [comment]
I think this may have been a consistency issue.  The example constructor assigned `this.power`.

I'm fine with the leading underscore.

@jrhorn424: Should we leave open until the idea is captured in the README?

**Comment by jrhorn424** [comment]
I'll make that change, thanks @gaand.

**Comment by jrhorn424** [comment]
I believe this is addressed in 5696491ba0b66e78b55fa914a95fe950e58118a8

**Comment by gaand** [comment]
Agreed.
